FROM ubuntu:22.04

RUN apt update -y && apt install -y python3 python3-pip && apt clean -y

ENV PIP_MIRROR="-i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ENV GENTRADE_CACHE_DIR="/app/cache/"

ADD requirements.txt /app/requirements.txt
ADD src/gentrade /app/gentrade
ADD apps/data_serv /app/data_serv
ENV PYTHONPATH=/app/

VOLUME [ "/app/cache/" ]
WORKDIR /app/

RUN pip install ${PIP_MIRROR} -r /app/data_serv/requirements.txt
RUN pip install ${PIP_MIRROR} -r /app/requirements.txt

EXPOSE 8000

ENTRYPOINT [ "uvicorn", "data_serv.data_serv:app", \
             "--host",  "0.0.0.0", \
             "--port", "8000" ]